# $Id: Makefile,v 1.11 2004/11/26 16:21:58 simonmar Exp $

TOP = ..
include $(TOP)/mk/boilerplate.mk

PACKAGE = concurrent
VERSION = 1.0

SRC_HC_OPTS += -fglasgow-exts -cpp

include $(TOP)/mk/target.mk
