#! /bin/sh

set -e

case "$1" in
    install|upgrade)
    ;;
 
    abort-upgrade)
    ;;
 
    *)
        echo "preinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

if test "$1" = "upgrade" && dpkg --compare-versions "$2" ge '1.4.199806-4' \
                         && dpkg --compare-versions "$2" lt '98.199905-1'
then
    update-alternatives --remove hugs /usr/bin/hugs1.4 
    update-alternatives --remove runhugs /usr/bin/runhugs1.4 
fi

#DEBHELPER#

exit 0
